# Generated by Django 2.1 on 2018-09-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='created',
        ),
    ]
