# Generated by Django 2.1 on 2018-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
