# Generated by Django 2.1 on 2018-09-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitaagroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='gapgroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='igapgroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='soroushgroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='created',
        ),
    ]
