# Generated by Django 2.1 on 2018-09-28 06:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='EitaaChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel_id', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/channels/telegramsorousheitaa')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Eitaa Channels',
            },
        ),
        migrations.CreateModel(
            name='GapChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel_id', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/channels/telegramsorousheitaaigapgap')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Gap Channels',
            },
        ),
        migrations.CreateModel(
            name='IGapChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel_id', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/channels/telegramsorousheitaaigap')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'IGap Channels',
            },
        ),
        migrations.CreateModel(
            name='SoroushChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel_id', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/channels/telegramsoroush')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Soroush Channels',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('channel_id', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/channels/telegram')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
    ]
