# Generated by Django 2.1 on 2018-09-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitaachannel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='gapchannel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='igapchannel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='soroushchannel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='telegramchannel',
            name='created',
        ),
    ]
