# Generated by Django 2.1 on 2018-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_eitaachannel_gapchannel_igapchannel_soroushchannel_telegramchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eitaachannel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='gapchannel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='igapchannel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='soroushchannel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='telegramchannel',
            name='link',
        ),
        migrations.AddField(
            model_name='eitaachannel',
            name='channel_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gapchannel',
            name='channel_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igapchannel',
            name='channel_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soroushchannel',
            name='channel_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='channel_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
