# Generated by Django 2.1 on 2018-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20180926_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eitaachannel',
            name='image',
            field=models.ImageField(upload_to='files/images/channels/telegramsorousheitaa'),
        ),
        migrations.AlterField(
            model_name='gapchannel',
            name='image',
            field=models.ImageField(upload_to='files/images/channels/telegramsorousheitaaigapgap'),
        ),
        migrations.AlterField(
            model_name='igapchannel',
            name='image',
            field=models.ImageField(upload_to='files/images/channels/telegramsorousheitaaigap'),
        ),
        migrations.AlterField(
            model_name='soroushchannel',
            name='image',
            field=models.ImageField(upload_to='files/images/channels/telegramsoroush'),
        ),
    ]
