# Generated by Django 2.1 on 2018-09-26 16:58

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20180926_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(upload_to=links.models.site_image_path),
        ),
    ]
