# Generated by Django 2.1 on 2018-09-27 06:45

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('links', '0005_auto_20180926_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('created', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='files/images/groups/')),
                ('types', models.CharField(choices=[('iran', 'ایرانی'), ('foreign', 'خارجی')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EitaaGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.CreateModel(
            name='GapGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.CreateModel(
            name='IGapGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.CreateModel(
            name='SoroushGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.CreateModel(
            name='WhatsappGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.Group')),
            ],
            bases=('links.group',),
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.Category'),
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
